name: Release
on:
  workflow_dispatch:
    inputs:
      method:
        description: |
          Which number to increment in the semantic versioning.
          Set 'major', 'minor' or 'patch'.
        required: true
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kyoh86/git-vertag-action@v1.1
        with:
          method: ${{ github.event.inputs.method }}
          push: true
  release:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: version tag
        run: |
          TAG_VERSION=$(git describe --tags --abbrev=0 --match='v*.*.*')
          git push origin $TAG_VERSION
      - name: Create a release pull request
        uses: bakunyo/git-pr-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: release
          GIT_PR_RELEASE_BRANCH_STAGING: master
          GIT_PR_RELEASE_LABELS: release
          NODE_VERSION: v${{ steps.package-version.outputs.current-version}}
          GIT_PR_RELEASE_TEMPLATE: .git-pr-release-template
