name: Release
on:
  workflow_dispatch:
    inputs:
      method:
        description: |
          Which number to increment in the semantic versioning.
          Set 'major', 'minor' or 'patch'.
        required: true
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kyoh86/git-vertag-action@v1.1
        with:
          method: ${{ github.event.inputs.method }}
          push: true
  release:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: version tag
        uses: bakunyo/git-pr-release-action@master
        run: |
          TAG_VERSION=$(git describe --tags --abbrev=0 --match='v*.*.*')
          git checkout -b release-$TAG_VERSION
          git push origin release-$TAG_VERSION
          echo "::set-output name=VERSION::${TAG_VERSION}"
       id: step-tag
      - name: Create a release pull request
        uses: bakunyo/git-pr-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: release-${{ steps.step-tag.outputs.VERSION }}
          GIT_PR_RELEASE_BRANCH_STAGING: master
          GIT_PR_RELEASE_LABELS: release-${{ steps.step-tag.outputs.VERSION }}
          GIT_PR_RELEASE_TEMPLATE: .git-pr-release-template
