name: Generate gRPC code
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: wizhi/setup-buf@v1
        with:
          version: "0.36.0"
      - uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
      - name: Install protoc-gen-go
        run: |
          go get -u google.golang.org/protobuf/cmd/protoc-gen-go
          go get -u google.golang.org/grpc/cmd/protoc-gen-go-grpc
      - name: Regenerate gRPC code
        run: |
          make build
      - name: Commit
        run: |
          git config user.name "gRPC Bot"
          git pull
          git commit -m "chore: regenerate grpc code"
          git push
